version: "3"
services:
  nb:
    image: nb
    ports:
      - 8888:8888
    volumes:
      - my_volume:/scraper
    environment:
      JUPYTER_TOKEN: "docker"
volumes:
  my_volume:
    external: true